plugins:
  issues.closed:
    - uses:
      - plugin: rndquu/conversation-rewards@development
        with:
          evmNetworkId: 100
          evmPrivateEncrypted: "zyS350C9cVU5Tu1vPHU_rk0KsePmXuFwfBjvdY0YdmxZLBJKyGyrsYM3S4HIRfdLxDmaoSOzKpBW0UHUXXSJhZCRJb4-lSxzoHY9bBJ9JaoxioK5ARee4z7I9Td3S7rxxXCrScIvzuOlQCr8WiWRNhlpIsMaY81WrOI"
          erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
          incentives:
            userExtractor:
              enabled: true
              redeemTask: true
            dataPurge:
              enabled: true
            formattingEvaluator:
              multipliers:
                - role: [ ISSUE_SPECIFICATION ]
                  multiplier: 3
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.1
                    html:
                      br: 0
                      code: 5
                      p: 1
                      em: 0
                      img: 0
                      strong: 0
                      blockquote: 0
                      h1: 1
                      h2: 1
                      h3: 1
                      h4: 1
                      h5: 1
                      h6: 1
                      a: 5
                      li: 1
                      td: 1
                      hr: 0
                - role: [ ISSUE_AUTHOR ]
                  multiplier: 1
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.2
                - role: [ ISSUE_ASSIGNEE ]
                  multiplier: 0
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0
                - role: [ ISSUE_COLLABORATOR ]
                  multiplier: 1
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.1
                - role: [ ISSUE_CONTRIBUTOR ]
                  multiplier: 0.25
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.1
                - role: [ PULL_SPECIFICATION ]
                  multiplier: 0
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0
                - role: [ PULL_AUTHOR ]
                  multiplier: 0
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.2
                - role: [ PULL_ASSIGNEE ]
                  multiplier: 1
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.1
                - role: [ PULL_COLLABORATOR ]
                  multiplier: 1
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.1
                - role: [ PULL_CONTRIBUTOR ]
                  multiplier: 0.25
                  rewards:
                    regex:
                      "\\b\\w+\\b": 0.1
            permitGeneration:
              enabled: true
            githubComment:
              post: true
              debug: false
